### ISSUE TITLE
Set proper package metadata (Missing short description in app index, etc)

### ISSUE THREAD

**Issue by timmc** [orblivion/desert-atlas#30]
(Edit by @orblivion)

- [x] Various metadata in package def file
- [x] Proper signing key, which requires re-releasing the app (I made a temporary key for developing, that's why it's not tied to my name yet)
- [x] Give testers instructions on migrating their bookmarks to the new app.

(Original report by @timmc below)

---

When the app is installed, I see "one-to-three words" as the short description on its tile in the Apps view.

![image](https://github.com/orblivion/sandstorm-share-a-map/assets/78608/74f12bf3-8b70-4bb5-92e2-e31e090b17bd)

**Comment by orblivion** [comment]
Hah, good point, thanks.

**Comment by orblivion** [comment]
Regarding category, I currently have it set to `other`:

https://docs.sandstorm.io/en/latest/developing/publishing-apps/#categories

I think I could make a case for `productivity`, given the bookmarking aspect:

> apps you use to get organized, not the apps you use to produce content. (Examples: Note-taking apps, kanban boards, project management.)

But it doesn't fit very well so my plan is to keep `other` as well. But I'm open to input here.

**Comment by orblivion** [comment]
Released in appVersion 35, under the new app-id: https://apps.sandstorm.io/app/e5eaqnrqfrhgax1awtgw9uqayg42kcen2gkpynjs3j5mww7w3rp0?experimental=true

This is the old one: https://apps.sandstorm.io/app/m3ctajcm6nnpce287r0a4t52ackzv7p7mmffrw88nge64fp0m8yh?experimental=true it'll hopefully be removed before long.
